# Generated by Django 5.1.4 on 2024-12-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quesiton',
            new_name='question',
        ),
    ]
